//! File merge utilities for `crosslink init` — gitignore, MCP, settings.

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

// Section markers for idempotent gitignore management
pub(super) const GITIGNORE_SECTION_START: &str =
    "# === Crosslink managed (do not edit between markers) ===";
pub(super) const GITIGNORE_SECTION_END: &str = "# === End crosslink managed ===";

const GITIGNORE_MANAGED_SECTION: &str = "\
# .crosslink/ — machine-local state (never commit)
.crosslink/issues.db
.crosslink/issues.db-wal
.crosslink/issues.db-shm
.crosslink/agent.json
.crosslink/session.json
.crosslink/daemon.pid
.crosslink/daemon.log
.crosslink/last_test_run
.crosslink/.active-issue
.crosslink/keys/
.crosslink/.hub-cache/
.crosslink/.knowledge-cache/
.crosslink/.cache/
.crosslink/init-manifest.json
.crosslink/init-manifest.json.tmp
.crosslink/hook-config.local.json
.crosslink/integrations/
.crosslink/rules.local/

# .crosslink/ — DO track these (project-level policy):
#   .crosslink/hook-config.json   — shared team configuration
#   .crosslink/rules/             — project coding standards
#   .crosslink/.gitignore         — inner gitignore for agent files

# .claude/ — auto-generated by crosslink init (not project source)
.claude/hooks/
.claude/commands/
.claude/mcp/

# .claude/ — DO track these (if manually configured):
#   .claude/settings.json         — Claude Code project settings
#   .claude/settings.local.json is per-developer, ignore separately if needed

# .agents/ — auto-generated by crosslink init (not project source)
.agents/hooks/
.agents/skills/
.agents/mcp/

# .agents/ — DO track these (if manually configured):
#   mcp_config.json               — Antigravity MCP server config
#   AGENTS.md                     — project instructions for Antigravity
";

/// Write or update a managed section in the project root `.gitignore`.
///
/// The section is delimited by `GITIGNORE_SECTION_START` / `GITIGNORE_SECTION_END` markers.
/// On first run the section is appended; on subsequent runs the existing section is replaced
pub(super) fn write_root_gitignore(project_root: &Path) -> Result<()> {
    let gitignore_path = project_root.join(".gitignore");

    let managed_block =
        format!("{GITIGNORE_SECTION_START}\n{GITIGNORE_MANAGED_SECTION}{GITIGNORE_SECTION_END}\n");

    let existing = fs::read_to_string(&gitignore_path).unwrap_or_default();

    let new_content = if let (Some(start_pos), Some(end_pos)) = (
        existing.find(GITIGNORE_SECTION_START),
        existing.find(GITIGNORE_SECTION_END),
    ) {
        // Replace existing managed section in-place
        let before = &existing[..start_pos];
        let after = &existing[end_pos + GITIGNORE_SECTION_END.len()..];
        // Strip leading newline from `after` so we don't accumulate blank lines
        let after = after.strip_prefix('\n').unwrap_or(after);
        format!("{before}{managed_block}{after}")
    } else {
        // Append new section (with a blank separator if file has content)
        if existing.is_empty() {
            managed_block
        } else {
            let separator = if existing.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            format!("{existing}{separator}{managed_block}")
        }
    };

    fs::write(&gitignore_path, new_content).context("Failed to write .gitignore")?;
    Ok(())
}

/// Merge crosslink's MCP server entries into an existing `.mcp.json`, or create it fresh.
use super::{AGY_MCP_CONFIG_JSON, MCP_JSON, PYTHON_PREFIX_PLACEHOLDER, SETTINGS_JSON};

pub(super) fn write_mcp_json_merged(mcp_path: &Path) -> Result<Vec<String>> {
    write_mcp_json_merged_from(mcp_path, MCP_JSON)
}

/// Merge Antigravity MCP servers (`.agents/mcp/`) into `.mcp.json`.
/// Used when `--runtime antigravity` is set without Claude, so Antigravity
/// still gets MCP server access via the project-root `.mcp.json` it reads.
pub(super) fn write_mcp_json_merged_agy(mcp_path: &Path) -> Result<Vec<String>> {
    write_mcp_json_merged_from(mcp_path, AGY_MCP_CONFIG_JSON)
}

fn write_mcp_json_merged_from(mcp_path: &Path, template: &str) -> Result<Vec<String>> {
    let embedded: serde_json::Value = serde_json::from_str(template)
        .context("embedded MCP template is not valid JSON — this is a build defect")?;
    let src_servers = embedded
        .get("mcpServers")
        .and_then(|v| v.as_object())
        .context("embedded MCP_JSON missing mcpServers object — this is a build defect")?;

    let mut obj = match fs::read_to_string(mcp_path) {
        Ok(raw) => {
            let parsed: serde_json::Value = serde_json::from_str(&raw).with_context(|| {
                format!(
                    "Existing .mcp.json at {} contains invalid JSON — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    mcp_path.display()
                )
            })?;
            match parsed {
                serde_json::Value::Object(map) => map,
                _ => anyhow::bail!(
                    "Existing .mcp.json at {} is not a JSON object — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    mcp_path.display()
                ),
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::Map::new(),
        Err(e) => return Err(anyhow::Error::from(e).context("Failed to read existing .mcp.json")),
    };

    let mut dest_map = match obj.remove("mcpServers") {
        Some(serde_json::Value::Object(map)) => map,
        Some(_) => anyhow::bail!(
            "Existing .mcp.json has a non-object mcpServers value — \
             refusing to overwrite. Fix or remove it, then retry."
        ),
        None => serde_json::Map::new(),
    };

    let mut warnings = Vec::new();
    for (key, value) in src_servers {
        if dest_map.contains_key(key) {
            warnings.push(format!(
                "Warning: overwriting existing mcpServers entry \"{key}\" with crosslink default"
            ));
        }
        dest_map.insert(key.clone(), value.clone());
    }

    obj.insert("mcpServers".into(), serde_json::Value::Object(dest_map));

    let mut output = serde_json::to_string_pretty(&serde_json::Value::Object(obj))
        .context("Failed to serialize .mcp.json")?;
    output.push('\n');
    fs::write(mcp_path, output).context("Failed to write .mcp.json")?;
    Ok(warnings)
}

// Section markers for idempotent AGENTS.md management
pub(super) const AGENTS_MD_SECTION_START: &str = "<!-- crosslink-managed-start -->";
pub(super) const AGENTS_MD_SECTION_END: &str = "<!-- crosslink-managed-end -->";

const AGENTS_MD_MANAGED_BLOCK: &str = "\
This repository uses [crosslink](https://github.com/forecast-bio/crosslink) for AI agent coordination.

**Required workflow:**
- Start every session: `crosslink session start`
- Track work: `crosslink session work <id>`
- End sessions: `crosslink session end --notes \"...\"`
- Create issues before writing code: `crosslink quick \"title\" -p <priority>`

Rules and behavioral guards are injected via `.agents/hooks/`. Do not bypass them.\
";

/// Write or update the crosslink managed block in `AGENTS.md`.
///
/// If `AGENTS.md` doesn't exist: creates it with just the managed block.
/// If it exists without markers: appends the block.
/// If it exists with markers: replaces the block in-place (idempotent).
pub(super) fn write_agents_md(project_root: &Path) -> Result<()> {
    let agents_md_path = project_root.join("AGENTS.md");

    let managed_block =
        format!("{AGENTS_MD_SECTION_START}\n{AGENTS_MD_MANAGED_BLOCK}\n{AGENTS_MD_SECTION_END}\n");

    let existing = fs::read_to_string(&agents_md_path).unwrap_or_default();

    let new_content = if let (Some(start_pos), Some(end_pos)) = (
        existing.find(AGENTS_MD_SECTION_START),
        existing.find(AGENTS_MD_SECTION_END),
    ) {
        let before = &existing[..start_pos];
        let after = &existing[end_pos + AGENTS_MD_SECTION_END.len()..];
        let after = after.strip_prefix('\n').unwrap_or(after);
        format!("{before}{managed_block}{after}")
    } else if existing.is_empty() {
        managed_block
    } else {
        let separator = if existing.ends_with('\n') {
            "\n"
        } else {
            "\n\n"
        };
        format!("{existing}{separator}{managed_block}")
    };

    fs::write(&agents_md_path, new_content).context("Failed to write AGENTS.md")?;
    Ok(())
}

/// Merge crosslink's hook set into an existing `.agents/hooks.json`, or create it fresh.
///
/// The file is a named top-level object map. Crosslink owns the `"crosslink"` key.
/// All other keys are preserved untouched.
pub(super) fn write_hooks_json_merged(hooks_json_path: &Path, content: &str) -> Result<()> {
    let new_crosslink: serde_json::Value = serde_json::from_str(content)
        .context("antigravity hooks.json template is not valid JSON — this is a build defect")?;

    let crosslink_entry = new_crosslink
        .get("crosslink")
        .context("antigravity hooks.json template missing 'crosslink' key — build defect")?;

    let mut obj = match fs::read_to_string(hooks_json_path) {
        Ok(raw) => {
            let parsed: serde_json::Value = serde_json::from_str(&raw).with_context(|| {
                format!(
                    "Existing hooks.json at {} contains invalid JSON — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    hooks_json_path.display()
                )
            })?;
            match parsed {
                serde_json::Value::Object(map) => map,
                _ => anyhow::bail!(
                    "Existing hooks.json at {} is not a JSON object — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    hooks_json_path.display()
                ),
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::Map::new(),
        Err(e) => return Err(anyhow::Error::from(e).context("Failed to read existing hooks.json")),
    };

    obj.insert("crosslink".into(), crosslink_entry.clone());

    let mut output = serde_json::to_string_pretty(&serde_json::Value::Object(obj))
        .context("Failed to serialize hooks.json")?;
    output.push('\n');
    fs::write(hooks_json_path, output).context("Failed to write hooks.json")?;
    Ok(())
}

/// Merge crosslink's MCP server entries into an existing `mcp_config.json`, or create it fresh.
///
/// Adds crosslink's `mcpServers` keys; preserves user keys; skips crosslink keys already present.
pub(super) fn write_mcp_config_merged(
    mcp_config_path: &Path,
    content: &str,
) -> Result<Vec<String>> {
    let embedded: serde_json::Value = serde_json::from_str(content)
        .context("antigravity mcp_config.json template is not valid JSON — build defect")?;
    let src_servers = embedded
        .get("mcpServers")
        .and_then(|v| v.as_object())
        .context("antigravity mcp_config.json template missing mcpServers — build defect")?;

    let mut obj = match fs::read_to_string(mcp_config_path) {
        Ok(raw) => {
            let parsed: serde_json::Value = serde_json::from_str(&raw).with_context(|| {
                format!(
                    "Existing mcp_config.json at {} contains invalid JSON — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    mcp_config_path.display()
                )
            })?;
            match parsed {
                serde_json::Value::Object(map) => map,
                _ => anyhow::bail!(
                    "Existing mcp_config.json at {} is not a JSON object — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    mcp_config_path.display()
                ),
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::Map::new(),
        Err(e) => {
            return Err(anyhow::Error::from(e).context("Failed to read existing mcp_config.json"))
        }
    };

    let mut dest_map = match obj.remove("mcpServers") {
        Some(serde_json::Value::Object(map)) => map,
        Some(_) => anyhow::bail!(
            "Existing mcp_config.json has a non-object mcpServers value — \
             refusing to overwrite. Fix or remove it, then retry."
        ),
        None => serde_json::Map::new(),
    };

    let mut warnings = Vec::new();
    for (key, value) in src_servers {
        if dest_map.contains_key(key) {
            warnings.push(format!(
                "Warning: overwriting existing mcpServers entry \"{key}\" with crosslink default"
            ));
        }
        dest_map.insert(key.clone(), value.clone());
    }

    obj.insert("mcpServers".into(), serde_json::Value::Object(dest_map));

    let mut output = serde_json::to_string_pretty(&serde_json::Value::Object(obj))
        .context("Failed to serialize mcp_config.json")?;
    output.push('\n');
    fs::write(mcp_config_path, output).context("Failed to write mcp_config.json")?;
    Ok(warnings)
}

/// Merge crosslink's default `allowedTools` into an existing `.claude/settings.json`,
/// or create it fresh.  Hooks are always overwritten (they are crosslink-managed),
/// but user-added `allowedTools` entries are preserved.
///
/// The `python_prefix` is substituted into hook commands via the `__PYTHON_PREFIX__`
pub(super) fn write_settings_json_merged(settings_path: &Path, python_prefix: &str) -> Result<()> {
    let template_raw = SETTINGS_JSON.replace(PYTHON_PREFIX_PLACEHOLDER, python_prefix);
    let template: serde_json::Value = serde_json::from_str(&template_raw).context(
        "embedded SETTINGS_JSON is not valid JSON after substitution — this is a build defect",
    )?;

    let embedded_tools: Vec<String> = template
        .get("allowedTools")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    let mut obj = match fs::read_to_string(settings_path) {
        Ok(raw) => {
            let parsed: serde_json::Value = serde_json::from_str(&raw).with_context(|| {
                format!(
                    "Existing settings.json at {} contains invalid JSON — \
                         refusing to overwrite. Fix or remove it, then retry.",
                    settings_path.display()
                )
            })?;
            match parsed {
                serde_json::Value::Object(map) => map,
                _ => anyhow::bail!(
                    "Existing settings.json at {} is not a JSON object — \
                     refusing to overwrite. Fix or remove it, then retry.",
                    settings_path.display()
                ),
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::Map::new(),
        Err(e) => {
            return Err(anyhow::Error::from(e).context("Failed to read existing settings.json"))
        }
    };

    // Merge allowedTools: union of existing entries + embedded defaults (no duplicates)
    let mut tools: Vec<String> = obj
        .get("allowedTools")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    for tool in &embedded_tools {
        if !tools.contains(tool) {
            tools.push(tool.clone());
        }
    }

    obj.insert(
        "allowedTools".into(),
        serde_json::Value::Array(tools.into_iter().map(serde_json::Value::String).collect()),
    );

    // Overwrite hooks (crosslink-managed) and enableAllProjectMcpServers
    if let Some(hooks) = template.get("hooks") {
        obj.insert("hooks".into(), hooks.clone());
    }
    if let Some(enable) = template.get("enableAllProjectMcpServers") {
        obj.insert("enableAllProjectMcpServers".into(), enable.clone());
    }

    let mut output = serde_json::to_string_pretty(&serde_json::Value::Object(obj))
        .context("Failed to serialize settings.json")?;
    output.push('\n');
    fs::write(settings_path, output).context("Failed to write settings.json")?;
    Ok(())
}
